// <auto-generated />
using AdRackHub.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AdRackHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260727240000_AddBillingRunInvoiceReceivedDate")]
    partial class AddBillingRunInvoiceReceivedDate
    {
    }
}
